//
// File generated by rootcint at Wed Sep 10 13:56:35 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME CFD_Tab_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "CFD_Tab_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CFD_Tab_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_CFD_Tab(void *p);
   static void deleteArray_CFD_Tab(void *p);
   static void destruct_CFD_Tab(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CFD_Tab*)
   {
      ::CFD_Tab *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CFD_Tab >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CFD_Tab", ::CFD_Tab::Class_Version(), "./include/CFD_Tab.h", 58,
                  typeid(::CFD_Tab), DefineBehavior(ptr, ptr),
                  &::CFD_Tab::Dictionary, isa_proxy, 4,
                  sizeof(::CFD_Tab) );
      instance.SetDelete(&delete_CFD_Tab);
      instance.SetDeleteArray(&deleteArray_CFD_Tab);
      instance.SetDestructor(&destruct_CFD_Tab);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CFD_Tab*)
   {
      return GenerateInitInstanceLocal((::CFD_Tab*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CFD_Tab*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr CFD_Tab::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *CFD_Tab::Class_Name()
{
   return "CFD_Tab";
}

//______________________________________________________________________________
const char *CFD_Tab::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CFD_Tab*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CFD_Tab::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CFD_Tab*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CFD_Tab::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CFD_Tab*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CFD_Tab::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CFD_Tab*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void CFD_Tab::Streamer(TBuffer &R__b)
{
   // Stream an object of class CFD_Tab.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(CFD_Tab::Class(),this);
   } else {
      R__b.WriteClassBuffer(CFD_Tab::Class(),this);
   }
}

//______________________________________________________________________________
void CFD_Tab::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CFD_Tab.
      TClass *R__cl = ::CFD_Tab::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQObject", &fQObject);
      R__insp.InspectMember(fQObject, "fQObject.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBoardList", &fBoardList);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCFDList", &fCFDList);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDACList", &fDACList);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fValList[3]", &fValList);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDACName[3]", &fDACName);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fReadValButton", &fReadValButton);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fSetValButton", &fSetValButton);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBoardFile", &fBoardFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fReadBoardFile", &fReadBoardFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fReadCFDStruct", &fReadCFDStruct);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCFDStructFile", &fCFDStructFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBoardPorts", &fBoardPorts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCFDs", &fCFDs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNBoards", &fNBoards);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNCFD", &fNCFD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fValChanged[3]", fValChanged);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fSelectedBoard", &fSelectedBoard);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fSelectedCFD", &fSelectedCFD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fGen", (void*)&fGen);
      R__insp.InspectMember("IDGen", (void*)&fGen, "fGen.", false);
      TGCompositeFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_CFD_Tab(void *p) {
      delete ((::CFD_Tab*)p);
   }
   static void deleteArray_CFD_Tab(void *p) {
      delete [] ((::CFD_Tab*)p);
   }
   static void destruct_CFD_Tab(void *p) {
      typedef ::CFD_Tab current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CFD_Tab

/********************************************************
* CFD_Tab_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableCFD_Tab_Dict();

extern "C" void G__set_cpp_environmentCFD_Tab_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("include/CFD_Tab.h");
  G__cpp_reset_tagtableCFD_Tab_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevCFD_Tab_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CFD_Tab */
static int G__CFD_Tab_Dict_313_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const CFD_Tab*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((CFD_Tab*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((CFD_Tab*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((CFD_Tab*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((CFD_Tab*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((CFD_Tab*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((CFD_Tab*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CFD_Tab* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new CFD_Tab((TGWindow*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) CFD_Tab((TGWindow*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((CFD_Tab*) G__getstructoffset())->ReadBoardListFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((CFD_Tab*) G__getstructoffset())->ReadCFDStructFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->ReadFiles();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((CFD_Tab*) G__getstructoffset())->ConnectBoards());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((CFD_Tab*) G__getstructoffset())->AddBoardCFDs());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((CFD_Tab*) G__getstructoffset())->AddCFDDACs());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((CFD_Tab*) G__getstructoffset())->SetDACVal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((CFD_Tab*) G__getstructoffset())->GetDACVal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->ReadDACVal();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->ThrChanged();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->WidthChanged();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->OffChanged();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CFD_Tab::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CFD_Tab::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CFD_Tab::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CFD_Tab::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CFD_Tab*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CFD_Tab::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CFD_Tab::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CFD_Tab::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CFD_Tab_Dict_313_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CFD_Tab::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CFD_Tab G__TCFD_Tab;
static int G__CFD_Tab_Dict_313_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CFD_Tab*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CFD_Tab*) (soff+(sizeof(CFD_Tab)*i)))->~G__TCFD_Tab();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CFD_Tab*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CFD_Tab*) (soff))->~G__TCFD_Tab();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CFD_Tab */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncCFD_Tab_Dict {
 public:
  G__Sizep2memfuncCFD_Tab_Dict(): p(&G__Sizep2memfuncCFD_Tab_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncCFD_Tab_Dict::*p)();
};

size_t G__get_sizep2memfuncCFD_Tab_Dict()
{
  G__Sizep2memfuncCFD_Tab_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceCFD_Tab_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab))) {
     CFD_Tab *G__Lderived;
     G__Lderived=(CFD_Tab*)0x1000;
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab),G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab),G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab),G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab),G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab),G__get_linked_tagnum(&G__CFD_Tab_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab),G__get_linked_tagnum(&G__CFD_Tab_DictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableCFD_Tab_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__CFD_Tab_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CFD_Tab */
static void G__setup_memvarCFD_Tab(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab));
   { CFD_Tab *p; p=(CFD_Tab*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGListBox),-1,-1,4,"fBoardList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGListBox),-1,-1,4,"fCFDList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGListBox),-1,-1,4,"fDACList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGComboBox),-1,-1,4,"fValList[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGTextView),-1,-1,4,"fDACName[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGTextButton),-1,-1,4,"fReadValButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGTextButton),-1,-1,4,"fSetValButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGTextEdit),-1,-1,4,"fBoardFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGTextButton),-1,-1,4,"fReadBoardFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGTextButton),-1,-1,4,"fReadCFDStruct=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TGTextEdit),-1,-1,4,"fCFDStructFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_USBCom),-1,-1,4,"fBoardPorts=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD),-1,-1,4,"fCFDs=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fNBoards=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fNCFD=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fValChanged[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_USBCom),-1,-1,4,"fSelectedBoard=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD),-1,-1,4,"fSelectedCFD=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_IDGen),-1,-1,4,"fGen=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CFD_Tab_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarCFD_Tab_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCFD_Tab(void) {
   /* CFD_Tab */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab));
   G__memfunc_setup("GetListOfSignals",1602,G__CFD_Tab_Dict_313_0_1, 85, G__get_linked_tagnum(&G__CFD_Tab_DictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__CFD_Tab_Dict_313_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__CFD_Tab_Dict_313_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LowPriority",1172,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EmitVA",550,G__CFD_Tab_Dict_313_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__CFD_Tab_Dict_313_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ChangedBy",869,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Message",709,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CFD_Tab",579,G__CFD_Tab_Dict_313_0_26, 105, G__get_linked_tagnum(&G__CFD_Tab_DictLN_CFD_Tab), -1, 0, 1, 1, 1, 0, "U 'TGWindow' - 0 - parent", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadBoardListFile",1664,G__CFD_Tab_Dict_313_0_27, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadCFDStructFile",1614,G__CFD_Tab_Dict_313_0_28, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadFiles",879,G__CFD_Tab_Dict_313_0_29, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ConnectBoards",1317,G__CFD_Tab_Dict_313_0_30, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddBoardCFDs",1073,G__CFD_Tab_Dict_313_0_31, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddCFDDACs",785,G__CFD_Tab_Dict_313_0_32, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDACVal",791,G__CFD_Tab_Dict_313_0_33, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDACVal",779,G__CFD_Tab_Dict_313_0_34, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadDACVal",871,G__CFD_Tab_Dict_313_0_35, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ThrChanged",984,G__CFD_Tab_Dict_313_0_36, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("WidthChanged",1194,G__CFD_Tab_Dict_313_0_37, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OffChanged",965,G__CFD_Tab_Dict_313_0_38, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__CFD_Tab_Dict_313_0_39, 85, G__get_linked_tagnum(&G__CFD_Tab_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CFD_Tab::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__CFD_Tab_Dict_313_0_40, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CFD_Tab::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__CFD_Tab_Dict_313_0_41, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CFD_Tab::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__CFD_Tab_Dict_313_0_42, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CFD_Tab::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__CFD_Tab_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__CFD_Tab_Dict_313_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__CFD_Tab_Dict_313_0_47, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CFD_Tab::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__CFD_Tab_Dict_313_0_48, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CFD_Tab::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__CFD_Tab_Dict_313_0_49, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CFD_Tab::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__CFD_Tab_Dict_313_0_50, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CFD_Tab::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~CFD_Tab", 705, G__CFD_Tab_Dict_313_0_51, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncCFD_Tab_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalCFD_Tab_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcCFD_Tab_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__CFD_Tab_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_USBCom = { "USBCom" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_CFD = { "CFD" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGListBox = { "TGListBox" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGTextView = { "TGTextView" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_TGTextEdit = { "TGTextEdit" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_IDGen = { "IDGen" , 99 , -1 };
G__linked_taginfo G__CFD_Tab_DictLN_CFD_Tab = { "CFD_Tab" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableCFD_Tab_Dict() {
  G__CFD_Tab_DictLN_TClass.tagnum = -1 ;
  G__CFD_Tab_DictLN_TBuffer.tagnum = -1 ;
  G__CFD_Tab_DictLN_TMemberInspector.tagnum = -1 ;
  G__CFD_Tab_DictLN_TObject.tagnum = -1 ;
  G__CFD_Tab_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CFD_Tab_DictLN_TList.tagnum = -1 ;
  G__CFD_Tab_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__CFD_Tab_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGObject.tagnum = -1 ;
  G__CFD_Tab_DictLN_TQObject.tagnum = -1 ;
  G__CFD_Tab_DictLN_TQObjSender.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGWindow.tagnum = -1 ;
  G__CFD_Tab_DictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__CFD_Tab_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGFrame.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGCompositeFrame.tagnum = -1 ;
  G__CFD_Tab_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGTextButton.tagnum = -1 ;
  G__CFD_Tab_DictLN_USBCom.tagnum = -1 ;
  G__CFD_Tab_DictLN_CFD.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGListBox.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGComboBox.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGTextView.tagnum = -1 ;
  G__CFD_Tab_DictLN_TGTextEdit.tagnum = -1 ;
  G__CFD_Tab_DictLN_IDGen.tagnum = -1 ;
  G__CFD_Tab_DictLN_CFD_Tab.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableCFD_Tab_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TList);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_USBCom);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_CFD);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGListBox);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGTextView);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_TGTextEdit);
   G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_IDGen);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__CFD_Tab_DictLN_CFD_Tab),sizeof(CFD_Tab),-1,324608,(char*)NULL,G__setup_memvarCFD_Tab,G__setup_memfuncCFD_Tab);
}
extern "C" void G__cpp_setupCFD_Tab_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupCFD_Tab_Dict()");
  G__set_cpp_environmentCFD_Tab_Dict();
  G__cpp_setup_tagtableCFD_Tab_Dict();

  G__cpp_setup_inheritanceCFD_Tab_Dict();

  G__cpp_setup_typetableCFD_Tab_Dict();

  G__cpp_setup_memvarCFD_Tab_Dict();

  G__cpp_setup_memfuncCFD_Tab_Dict();
  G__cpp_setup_globalCFD_Tab_Dict();
  G__cpp_setup_funcCFD_Tab_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncCFD_Tab_Dict();
  return;
}
class G__cpp_setup_initCFD_Tab_Dict {
  public:
    G__cpp_setup_initCFD_Tab_Dict() { G__add_setup_func("CFD_Tab_Dict",(G__incsetup)(&G__cpp_setupCFD_Tab_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initCFD_Tab_Dict() { G__remove_setup_func("CFD_Tab_Dict"); }
};
G__cpp_setup_initCFD_Tab_Dict G__cpp_setup_initializerCFD_Tab_Dict;

