/********************************************************************
* CFD_Frame_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CFD_Frame_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCFD_Frame_Dict();
extern void G__cpp_setup_inheritanceCFD_Frame_Dict();
extern void G__cpp_setup_typetableCFD_Frame_Dict();
extern void G__cpp_setup_memvarCFD_Frame_Dict();
extern void G__cpp_setup_globalCFD_Frame_Dict();
extern void G__cpp_setup_memfuncCFD_Frame_Dict();
extern void G__cpp_setup_funcCFD_Frame_Dict();
extern void G__set_cpp_environmentCFD_Frame_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/CFD_MainFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CFD_Frame_DictLN_TClass;
extern G__linked_taginfo G__CFD_Frame_DictLN_TBuffer;
extern G__linked_taginfo G__CFD_Frame_DictLN_TMemberInspector;
extern G__linked_taginfo G__CFD_Frame_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CFD_Frame_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CFD_Frame_DictLN_TList;
extern G__linked_taginfo G__CFD_Frame_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CFD_Frame_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CFD_Frame_DictLN_TQObjSender;
extern G__linked_taginfo G__CFD_Frame_DictLN_TGMainFrame;
extern G__linked_taginfo G__CFD_Frame_DictLN_TGStatusBar;
extern G__linked_taginfo G__CFD_Frame_DictLN_CFD_MainFrame;

/* STUB derived class for protected member access */
